### ISSUE TITLE
Migrate from travis to prow for CI

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/pipeline-library#108]
@pabrahamsson ; am sure this is already on your radar but this is to just track the work.

Also, i know its been talked about on the weekly calls, but has it been decided on how someone can view/edit the prow config?

**Comment by pabrahamsson** [comment]
@garethahealy I've added a CI job to Prow for this repo. I'll leave this issue open until we see the github integration working properly on the next PR.

I'm looking into if we can use [CI Operator](https://github.com/openshift/release/blob/master/ci-operator) for sharing prow jobs/configs through a git repo.

**Comment by sabre1041** [comment]
@pabrahamsson great to see you have found the CI Operator

**Comment by pabrahamsson** [comment]
@garethahealy I'm running into issues with the Prow PR build due to how the remote repo is being cloned in the `_test/setup.sh`. The problem appears to be that the script expects the branch name but this information is not known to Prow. I can work around this pretty easily but there's also a git clone in [one of the roles](https://github.com/redhat-cop/pipeline-library/blob/master/roles/process-tests/tasks/main.yml#L23-L28).
I plan to do some more digging on the Prow side to see if I can work around it. If not, is there a specific need to use `git clone --single-branch --branch <name> `?

**Comment by garethahealy** [comment]
@pabrahamsson ; the idea behind that was; if you ran the setup script against a branch you'd not checked out, the script would check it out, and deploy those files. if we dont checkout that codebase, you'd create the wrong tests.

that make sense? if you can think of a different way of that working, happy to re-work it

**Comment by pabrahamsson** [comment]
Yep the part in the setup script absolutely makes sense @garethahealy and that part I can just skip in Prow (already done). What about the `process-tests` role changing the branch for the Sonarqube analysis, is this required?

**Comment by garethahealy** [comment]
Thats needed if someone ever changes the setup script for sonar:
- https://github.com/redhat-cop/pipeline-library/blob/master/test/create-sonarqube-installation.groovy

Unlikely to happen too often, but always good to keep in mind.
