### ISSUE TITLE
Add Example Pull Request Build Pipeline for mvn and npm

### ISSUE THREAD

**Issue by sherl0cks** [redhat-cop/pipeline-library#7]

**Comment by garethahealy** [comment]
@sherl0cks ; i know you've left RH, but can you provide more info or close please. Not 100% sure what the title is asking for.

**Comment by sherl0cks** [comment]
Unless it's changed, the existing OCP / Jenkins integration did not support Jenkins multibranch builds which are needed to build against PRs / branches - https://jenkins.io/doc/book/pipeline/multibranch/. The idea here was to show folks how to set up PR builds without departing from the native OCP / Jenkins integration @pcarney8 likely has this somewhere already and this is just out of date.

**Comment by pcarney8** [comment]
@garethahealy multi-branch builds for the OCP / Jenkins sync is still in-progress: https://github.com/openshift/jenkins-sync-plugin/issues/190 PR is still WIP here: https://github.com/openshift/jenkins-sync-plugin/pull/310

Yes and to @sherl0cks point, we were just trying to build in an example due to multi-branch not being there. If @garethahealy you have an example of one feel free to add it, I believe I've got one floating around but it might take some time to dig up. This issue is still relevant.

**Comment by InfoSec812** [comment]
Issue is still relevant...
